-d C:\GitHub\NanoMig-TN20K-Deluxe-Edition\src\impl\gwsynthesis\nanomig.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\GitHub\NanoMig-TN20K-Deluxe-Edition\src\tang-nano20K\nanomig.cst
-cfg C:\GitHub\NanoMig-TN20K-Deluxe-Edition\src\impl\pnr\device.cfg
-sdc C:\GitHub\NanoMig-TN20K-Deluxe-Edition\src\tang-nano20K\nanomig.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 2
-route_option 1
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
